
@rooturl = http://localhost:8080/api/v1/ft
@userEp = {{rooturl}}/users
@transactionEp= {{rooturl}}/transactions

POST {{userEp}}/register
Content-Type: application/json

{
    "username":"ishwor karki",
    "email":"bauu@gmail.com",
    "password":"passwordthaxaina"
}

###

POST {{userEp}}/login
Content-Type: application/json

{
    "email":"bauu@gmail.com",
    "password":"passwordthaxaina"
}

###
POST {{transactionEp}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhdXVAZ21haWwuY29tIiwiaWF0IjoxNzM4MDIwNzI5LCJleHAiOjE3MzgxMDcxMjl9.aY6wPlEcFtYxRE8PfU1W8AeBl_xj-t5c8-JpqgpgVUw

{
    "type":"Expense",
    "amount":200,
    "date":"10-10-2020",
    "description":"by bauuuuu"
}

###
GET {{transactionEp}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhdXVAZ21haWwuY29tIiwiaWF0IjoxNzM4MDIwNzI5LCJleHAiOjE3MzgxMDcxMjl9.aY6wPlEcFtYxRE8PfU1W8AeBl_xj-t5c8-JpqgpgVUw
###
DELETE {{transactionEp}}/678f21621499a7dca28904f2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhdXVAZ21haWwuY29tIiwiaWF0IjoxNzM4MDIwNzI5LCJleHAiOjE3MzgxMDcxMjl9.aY6wPlEcFtYxRE8PfU1W8AeBl_xj-t5c8-JpqgpgVUw


###
DELETE {{transactionEp}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhdXVAZ21haWwuY29tIiwiaWF0IjoxNzM4MDIwNzI5LCJleHAiOjE3MzgxMDcxMjl9.aY6wPlEcFtYxRE8PfU1W8AeBl_xj-t5c8-JpqgpgVUw

{
    "transactionsid":[
        "67981907ca4e081ac96f93dd",
        "6798178625189bf644fd192c"
    ]
}